sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.3

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer update
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpstan" ]] ; then
      composer update
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpunit" ]] ; then
      composer update
    fi
  - |
    if [[ "$WP_TRAVISCI" == "coverage" ]] ; then
      composer update
    fi
script:
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      ./vendor/bin/phpcs --standard=phpcs.xml
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpstan" ]] ; then
      ./vendor/bin/phpstan analyse -c phpstan.neon
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpunit" ]] ; then
      ./vendor/bin/phpunit --configuration phpunit.xml
    fi
  - |
    if [[ "$WP_TRAVISCI" == "coverage" ]] ; then
      ./vendor/bin/coverage-check ./results/clover.xml 90
    fi
