name: Code Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Configure PHP 7.3
        uses: shivammathur/setup-php@v2
        env:
          runner: self-hosted
        with:
          php-version: '7.3'

      - name: Checkout code
        uses: actions/checkout@v2
        env:
          runner: self-hosted

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check Coding Standards
        run: composer run-script phpcs

      - name: Check Static Analysis
        run: composer run-script phpstan

      - name: Run Unit Testing
        run: composer run-script phpunit

      - name: Check Code Coverage
        run: composer run-script coverage